# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 15:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ss.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('code', models.CharField(blank=True, default=ss.utils.random_long_string, max_length=40, primary_key=True, serialize=False, verbose_name='邀请码')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('plan', models.CharField(choices=[('free', 'Free')], default='free', max_length=32, verbose_name='类型')),
                ('server', models.CharField(max_length=128, verbose_name='服务器')),
                ('method', models.CharField(choices=[('aes-256-cfb', 'aes-256-cfb')], default='aes-256-cfb', max_length=32, verbose_name='加密类型')),
                ('info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='简介')),
                ('status', models.CharField(choices=[('ok', 'OK')], default='ok', max_length=32, verbose_name='状态')),
                ('weight', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='SSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free')], default='free', max_length=32, verbose_name='套餐')),
                ('last_check_in_time', models.DateTimeField(editable=False, null=True, verbose_name='最后签到时间')),
                ('password', models.CharField(db_column='passwd', default=ss.utils.random_short_string, max_length=32, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='ShadowSocks密码')),
                ('port', models.IntegerField(db_column='port', unique=True, verbose_name='端口')),
                ('last_use_time', models.IntegerField(db_column='t', default=0, help_text='时间戳', verbose_name='最后使用时间')),
                ('upload_traffic', models.BigIntegerField(db_column='u', default=0, verbose_name='上传流量')),
                ('download_traffic', models.BigIntegerField(db_column='d', default=0, verbose_name='下载流量')),
                ('transfer_enable', models.BigIntegerField(db_column='transfer_enable', default=10737418240, verbose_name='总流量')),
                ('invite_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by', to='ss.InviteCode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ss_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_check_in_time',),
            },
        ),
        migrations.AddField(
            model_name='invitecode',
            name='user',
            field=models.ForeignKey(blank=True, help_text='不选择用户生成的验证码将公开', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='ss.SSUser'),
        ),
    ]
