# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssuser',
            name='enable',
            field=models.BooleanField(db_column='enable', default=True, verbose_name='开启'),
        ),
        migrations.AddField(
            model_name='ssuser',
            name='switch',
            field=models.BooleanField(db_column='switch', default=True, verbose_name='switch'),
        ),
        migrations.AlterField(
            model_name='node',
            name='method',
            field=models.CharField(choices=[('aes-256-cfb', 'aes-256-cfb'), ('rc4-md5', 'rc4-md5'), ('salsa20', 'salsa20'), ('chacha20', 'chacha20')], default='aes-256-cfb', max_length=32, verbose_name='加密类型'),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('ok', '好用'), ('slow', '不好用'), ('fail', '坏了')], default='ok', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterModelTable(
            name='ssuser',
            table='user',
        ),
    ]
